"""fix_is_percentage_in_order

Revision ID: 20ad4333d6d9
Revises: efd00a7cfd14
Create Date: 2026-09-18 16:57:03.793901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ad4333d6d9'
down_revision: Union[str, Sequence[str], None] = 'efd00a7cfd14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'is_percentage')
    op.add_column('orders', sa.Column('is_percentage', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_percentage')
    op.add_column('order_items', sa.Column('is_percentage', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
