"""ref: branch location and img is optional

Revision ID: 2b18c3b67ed2
Revises: 7d48da91d7d3
Create Date: 2026-05-09 14:50:14.665970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b18c3b67ed2'
down_revision: Union[str, Sequence[str], None] = '7d48da91d7d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branch', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('branch', 'img',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_branch_id'), 'branch', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_branch_id'), table_name='branch')
    op.alter_column('branch', 'img',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('branch', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
