"""track stock 

Revision ID: 4e66a67a4b28
Revises: c3e61bb3084f
Create Date: 2026-06-04 17:41:18.252503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e66a67a4b28'
down_revision: Union[str, Sequence[str], None] = 'c3e61bb3084f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'cancelled', name='transferstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_branch_id'), 'stocks', ['branch_id'], unique=False)
    op.create_index(op.f('ix_stocks_product_id'), 'stocks', ['product_id'], unique=False)
    op.create_unique_constraint('uq_product_branch_stock', 'stocks', ['product_id', 'branch_id'])
    op.drop_constraint(op.f('stocks_branch_id_fkey'), 'stocks', type_='foreignkey')
    op.drop_constraint(op.f('stocks_product_id_fkey'), 'stocks', type_='foreignkey')
    op.create_foreign_key(None, 'stocks', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'stocks', 'branch', ['branch_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stocks', type_='foreignkey')
    op.drop_constraint(None, 'stocks', type_='foreignkey')
    op.create_foreign_key(op.f('stocks_product_id_fkey'), 'stocks', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('stocks_branch_id_fkey'), 'stocks', 'branch', ['branch_id'], ['id'])
    op.drop_constraint('uq_product_branch_stock', 'stocks', type_='unique')
    op.drop_index(op.f('ix_stocks_product_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_branch_id'), table_name='stocks')
    op.drop_table('stock_transfers')
    # ### end Alembic commands ###
