"""sku field nullable

Revision ID: 58aff4679ab9
Revises: c03e2364afb2
Create Date: 2026-09-17 17:40:26.812799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58aff4679ab9'
down_revision: Union[str, Sequence[str], None] = 'c03e2364afb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'sku_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'sku_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
