"""Add nullable note in order schema

Revision ID: 59865536cc6f
Revises: a8e939fed471
Create Date: 2026-06-01 19:37:37.446167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59865536cc6f'
down_revision: Union[str, Sequence[str], None] = 'a8e939fed471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'note')
    # ### end Alembic commands ###
