"""for coustomer only number is requierd

Revision ID: 6eb69a1814b0
Revises: 4e66a67a4b28
Create Date: 2026-06-10 19:24:33.934498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb69a1814b0'
down_revision: Union[str, Sequence[str], None] = '4e66a67a4b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=180),
               nullable=True)
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=180),
               nullable=False)
    # ### end Alembic commands ###
