"""stock_inbount_and_inbound_items

Revision ID: 737d4f3e3963
Revises: 7adfb302d62d
Create Date: 2026-09-12 11:33:53.144323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '737d4f3e3963'
down_revision: Union[str, Sequence[str], None] = '7adfb302d62d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_inbounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_no', sa.String(length=100), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_inbounds_branch_id'), 'stock_inbounds', ['branch_id'], unique=False)
    op.create_index(op.f('ix_stock_inbounds_id'), 'stock_inbounds', ['id'], unique=False)
    op.create_index(op.f('ix_stock_inbounds_invoice_no'), 'stock_inbounds', ['invoice_no'], unique=True)
    op.create_table('stock_inbound_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inbound_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inbound_id'], ['stock_inbounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_inbound_items_id'), 'stock_inbound_items', ['id'], unique=False)
    op.create_index(op.f('ix_stock_inbound_items_inbound_id'), 'stock_inbound_items', ['inbound_id'], unique=False)
    op.create_index(op.f('ix_stock_inbound_items_product_id'), 'stock_inbound_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_inbound_items_product_id'), table_name='stock_inbound_items')
    op.drop_index(op.f('ix_stock_inbound_items_inbound_id'), table_name='stock_inbound_items')
    op.drop_index(op.f('ix_stock_inbound_items_id'), table_name='stock_inbound_items')
    op.drop_table('stock_inbound_items')
    op.drop_index(op.f('ix_stock_inbounds_invoice_no'), table_name='stock_inbounds')
    op.drop_index(op.f('ix_stock_inbounds_id'), table_name='stock_inbounds')
    op.drop_index(op.f('ix_stock_inbounds_branch_id'), table_name='stock_inbounds')
    op.drop_table('stock_inbounds')
    # ### end Alembic commands ###
