"""Add relashonship between branch and user

Revision ID: 76f4407d659d
Revises: 88c7b4221b12
Create Date: 2026-05-10 10:23:10.059799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f4407d659d'
down_revision: Union[str, Sequence[str], None] = '88c7b4221b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('branch_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key(None, 'users', 'branch', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_branch_id', 'users', type_='foreignkey')
    op.drop_column('users', 'branch_id')
    # ### end Alembic commands ###
