"""change note size and add new status type

Revision ID: 79f86effa17b
Revises: 6c88b413cce2
Create Date: 2026-06-02 10:53:46.988056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79f86effa17b'
down_revision: Union[str, Sequence[str], None] = '6c88b413cce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
     # Add new enum values
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'processing'")
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'packing'")
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'out_for_delivery'")
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'delivered'")
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'completed'")
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'cancelled'")
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'refunded'")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
