"""add_address_details_and_add_phone_and_number_collumn

Revision ID: 7adfb302d62d
Revises: 5851c43e8bcb
Create Date: 2026-09-09 19:06:47.061316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7adfb302d62d'
down_revision: Union[str, Sequence[str], None] = '5851c43e8bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_addresses', sa.Column('division', sa.VARCHAR(length=30), nullable=True))
    op.add_column('customer_addresses', sa.Column('upzila', sa.VARCHAR(length=30), nullable=True))
    op.add_column('customer_addresses', sa.Column('phone', sa.VARCHAR(length=15), nullable=True))
    op.add_column('customer_addresses', sa.Column('name', sa.VARCHAR(length=15), nullable=True))
    op.alter_column('customer_addresses', 'city',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_addresses', 'city',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('customer_addresses', 'name')
    op.drop_column('customer_addresses', 'phone')
    op.drop_column('customer_addresses', 'upzila')
    op.drop_column('customer_addresses', 'division')
    # ### end Alembic commands ###
