"""hero_sliders_tbale_cahngefiled_image_url_to_img

Revision ID: 7d4532983983
Revises: c7a318fc2002
Create Date: 2026-08-10 18:02:24.201894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4532983983'
down_revision: Union[str, Sequence[str], None] = 'c7a318fc2002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('herosliders', sa.Column('img', sa.String(length=255), nullable=False))
    op.drop_column('herosliders', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('herosliders', sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('herosliders', 'img')
    # ### end Alembic commands ###
