"""add: product thumbnail

Revision ID: 7d48da91d7d3
Revises: 3dccc57e1291
Create Date: 2026-05-09 12:32:13.682504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d48da91d7d3'
down_revision: Union[str, Sequence[str], None] = '3dccc57e1291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_details_id'), 'product_details', ['id'], unique=False)
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    # op.add_column('products', sa.Column('is_buy_one_get_one', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column(
        'is_buy_one_get_one', 
        sa.Boolean(), 
        nullable=False, 
        server_default=sa.text('false') 
    ))
    op.add_column('products', sa.Column('thumbnail', sa.String(), nullable=True))
    op.alter_column('products', 'discount_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.drop_column('products', 'is_by_one_get_one')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_by_one_get_one', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('products', 'discount_percentage',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('products', 'thumbnail')
    op.drop_column('products', 'is_buy_one_get_one')
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_index(op.f('ix_product_details_id'), table_name='product_details')
    # ### end Alembic commands ###
