"""Add qty in product and string change to VARCHAR

Revision ID: 8d54fe99b8c6
Revises: 2b18c3b67ed2
Create Date: 2026-05-10 09:03:24.875637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d54fe99b8c6'
down_revision: Union[str, Sequence[str], None] = '2b18c3b67ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=False,server_default='0'))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'quantity')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    # ### end Alembic commands ###
