"""add cascade on delete in category and product table

Revision ID: ba2b4ad479cc
Revises: 76f4407d659d
Create Date: 2026-05-12 12:03:14.308186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2b4ad479cc'
down_revision: Union[str, Sequence[str], None] = '76f4407d659d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_details_product_id_fkey'), 'product_details', type_='foreignkey')
    op.create_foreign_key(None, 'product_details', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('product_images_product_id_fkey'), 'product_images', type_='foreignkey')
    op.create_foreign_key(None, 'product_images', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.create_foreign_key(op.f('product_images_product_id_fkey'), 'product_images', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'product_details', type_='foreignkey')
    op.create_foreign_key(op.f('product_details_product_id_fkey'), 'product_details', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
