"""track_extra_discount_is_percentage_or_amount

Revision ID: c03e2364afb2
Revises: 737d4f3e3963
Create Date: 2026-09-13 21:06:44.942472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c03e2364afb2'
down_revision: Union[str, Sequence[str], None] = '737d4f3e3963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('is_percentage', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'is_percentage')
    # ### end Alembic commands ###
