"""ref_stock_transfer_with_multiple_product

Revision ID: efd00a7cfd14
Revises: 58aff4679ab9
Create Date: 2026-09-17 21:09:43.837301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd00a7cfd14'
down_revision: Union[str, Sequence[str], None] = '58aff4679ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_transfer_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transfer_items_id'), 'stock_transfer_items', ['id'], unique=False)
    op.create_index(op.f('ix_stock_transfer_items_product_id'), 'stock_transfer_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_transfer_items_transfer_id'), 'stock_transfer_items', ['transfer_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_branch_id'), 'stock_transfers', ['branch_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_id'), 'stock_transfers', ['id'], unique=False)
    op.drop_constraint(op.f('stock_transfers_branch_id_fkey'), 'stock_transfers', type_='foreignkey')
    op.drop_constraint(op.f('stock_transfers_product_id_fkey'), 'stock_transfers', type_='foreignkey')
    op.create_foreign_key(None, 'stock_transfers', 'branch', ['branch_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('stock_transfers', 'product_id')
    op.drop_column('stock_transfers', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_transfers', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stock_transfers', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stock_transfers', type_='foreignkey')
    op.create_foreign_key(op.f('stock_transfers_product_id_fkey'), 'stock_transfers', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('stock_transfers_branch_id_fkey'), 'stock_transfers', 'branch', ['branch_id'], ['id'])
    op.drop_index(op.f('ix_stock_transfers_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_branch_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfer_items_transfer_id'), table_name='stock_transfer_items')
    op.drop_index(op.f('ix_stock_transfer_items_product_id'), table_name='stock_transfer_items')
    op.drop_index(op.f('ix_stock_transfer_items_id'), table_name='stock_transfer_items')
    op.drop_table('stock_transfer_items')
    # ### end Alembic commands ###
