"""add split payment fields to order

Revision ID: f78ade7c6f4a
Revises: 7d4532983983
Create Date: 2026-08-29 14:11:44.802615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f78ade7c6f4a'
down_revision: Union[str, Sequence[str], None] = '7d4532983983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cash_amount', sa.Numeric(precision=10, scale=2), server_default="0", nullable=False))
    op.add_column('orders', sa.Column('other_payment_method', sa.Enum('BKASH', 'NAGAD', 'ROCKET', name='paymentmethod'), nullable=True))
    op.add_column('orders', sa.Column('other_payment_amount', sa.Numeric(precision=10, scale=2), server_default="0", nullable=False))
    op.drop_column('orders', 'payment_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_method', postgresql.ENUM('CASH', 'BKASH', 'NAGAD', 'ROCKET', name='paymentmethod'), autoincrement=False, nullable=False))
    op.drop_column('orders', 'other_payment_amount')
    op.drop_column('orders', 'other_payment_method')
    op.drop_column('orders', 'cash_amount')
    # ### end Alembic commands ###
