"""oder: add order status

Revision ID: ff687d8360b9
Revises: ba2b4ad479cc
Create Date: 2026-05-19 21:06:03.390656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff687d8360b9'
down_revision: Union[str, Sequence[str], None] = 'ba2b4ad479cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    order_status_enum = sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', 'REFUNDED', name='orderstatus')
    order_status_enum.create(op.get_bind(), checkfirst=True)


    op.add_column('orders', sa.Column('status', order_status_enum, nullable=False))
    op.add_column('orders', sa.Column('delivery', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'extra_discount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'extra_discount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'delivery')
    # ### end Alembic commands ###
